---
  - hosts: "{{ host | default('ad3production') }}"
    become: yes
    roles:
      - { role: jdauphant.nginx }
      - { role: itcraftsmanpl.php7 }
      - joshualund.golang
    vars:
      nginx_sites: {}
      php_packages:
        - php7.1-common
        - php7.1-cli
        - php7.1-intl
        - php7.1-curl
        - php7.1-cgi
        - php7.1-fpm
        - php7.1-opcache
        - php7.1-json
        - php7.1-readline
        - php7.1-pgsql
        - php7.1-gd
        - php7.1-mbstring
        - php7.1-mcrypt
      php_timezone: UTC
